name: Python CI with Allure (Py 3.10 compatible)

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Clean allure-results
        run: |
          if [ -e allure-results ]; then rm -rf allure-results; fi
          mkdir -p allure-results

      - name: Patch collections for Py 3.10 and run tests
        run: |
          python compat_collections_patch.py
          pytest --alluredir=allure-results

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
