name: Python CI with Allure

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-allure-adaptor allure-pytest

      - name: Clean up allure-results directory
        run: |
          if [ -e allure-results ]; then
            rm -rf allure-results
          fi
          mkdir -p allure-results

      - name: Run tests with Allure
        run: |
          pytest --alluredir=allure-results
