name: Run Selenium Tests with Allure

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest
          # Install Allure Commandline (necessary for generating reports)
          sudo apt-get install allure

      - name: Run tests with Allure
        run: |
          pytest --alluredir=reports/

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: reports/

      - name: Generate Allure Report (Optional)
        run: |
          allure serve reports/  # This will start a local Allure server to view the report
